### ISSUE TITLE
无法通过npm run-script build 安装

### ISSUE THREAD

**Issue by knifecaojia** [AMTcommunity/vns-web3.js#1]
下面是log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\*\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run-script',
1 verbose cli   'build' ]
2 info using npm@6.9.0
3 info using node@v8.11.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle vns-web3@1.0.0-beta.36~prebuild: vns-web3@1.0.0-beta.36
6 info lifecycle vns-web3@1.0.0-beta.36~build: vns-web3@1.0.0-beta.36
7 verbose lifecycle vns-web3@1.0.0-beta.36~build: unsafe-perm in lifecycle true
8 verbose lifecycle vns-web3@1.0.0-beta.36~build: PATH: C:\Users\*\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;J:\ccboot\vns-web3.js-master\vns-web3.js-master\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\VanDyke Software\Clients\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\CodeSmith\v8.0\;D:\adb;C:\Program Files (x86)\Java\jre1.8.0_181\bin;C:\Program Files\Git\cmd;C:\Go\bin;C:\Users\*\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\*\AppData\Local\Programs\Python\Python36\;C:\Users\*\AppData\Local\Microsoft\WindowsApps;;C:\Users\*\AppData\Local\Programs\Fiddler;C:\Users\*\AppData\Roaming\npm;C:\Users\*\AppData\Local\Microsoft\WindowsApps;C:\Users\*\AppData\Local\Programs\Microsoft VS Code\bin
9 verbose lifecycle vns-web3@1.0.0-beta.36~build: CWD: J:\ccboot\vns-web3.js-master\vns-web3.js-master
10 silly lifecycle vns-web3@1.0.0-beta.36~build: Args: [ '/d /s /c', 'gulp' ]
11 silly lifecycle vns-web3@1.0.0-beta.36~build: Returned: code: 1  signal: null
12 info lifecycle vns-web3@1.0.0-beta.36~build: Failed to exec build script
13 verbose stack Error: vns-web3@1.0.0-beta.36 build: `gulp`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\*\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\*\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid vns-web3@1.0.0-beta.36
15 verbose cwd J:\ccboot\vns-web3.js-master\vns-web3.js-master
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\*\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "build"
18 verbose node v8.11.2
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error vns-web3@1.0.0-beta.36 build: `gulp`
22 error Exit status 1
23 error Failed at the vns-web3@1.0.0-beta.36 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by knifecaojia** [comment]
ubuntu 16 也一样
